/*
 * Hume
 * This is an API for Hume
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Hume) {
      root.Hume = {};
    }
    root.Hume.AddZoneRequest = factory(root.Hume.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AddZoneRequest model module.
   * @module model/AddZoneRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AddZoneRequest</code>.
   * @alias module:model/AddZoneRequest
   * @class
   * @param zoneId {Number} 
   * @param zoneName {String} 
   * @param zoneAlarm {Boolean} 
   * @param zoneTemp {Number} 
   */
  var exports = function(zoneId, zoneName, zoneAlarm, zoneTemp) {
    this.zoneId = zoneId;
    this.zoneName = zoneName;
    this.zoneAlarm = zoneAlarm;
    this.zoneTemp = zoneTemp;
  };

  /**
   * Constructs a <code>AddZoneRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddZoneRequest} obj Optional instance to populate.
   * @return {module:model/AddZoneRequest} The populated <code>AddZoneRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (Object.prototype.hasOwnProperty.call(data, 'zone_id'))
        obj.zoneId = ApiClient.convertToType(data['zone_id'], 'Number');
      if (Object.prototype.hasOwnProperty.call(data, 'zone_name'))
        obj.zoneName = ApiClient.convertToType(data['zone_name'], 'String');
      if (Object.prototype.hasOwnProperty.call(data, 'zone_alarm'))
        obj.zoneAlarm = ApiClient.convertToType(data['zone_alarm'], 'Boolean');
      if (Object.prototype.hasOwnProperty.call(data, 'zone_temp'))
        obj.zoneTemp = ApiClient.convertToType(data['zone_temp'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} zoneId
   */
  exports.prototype.zoneId = undefined;

  /**
   * @member {String} zoneName
   */
  exports.prototype.zoneName = undefined;

  /**
   * @member {Boolean} zoneAlarm
   */
  exports.prototype.zoneAlarm = undefined;

  /**
   * @member {Number} zoneTemp
   */
  exports.prototype.zoneTemp = undefined;


  return exports;

}));
