/*
 * Hume
 * This is an API for Hume
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto-generated by the Swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

// Import the module loader utility function
const configureModule = require('../moduleLoaderUtils');
// Import the test utility
const { generateInstanceTests } = require('../testUtils');

// Use the module loader utility function to configure the module
configureModule(function () {
  'use strict';

  // Generate test cases for CreateUserRequest class
  generateInstanceTests('CreateUserRequest', ['fullname', 'email', 'address', 'phone', 'city', 'username', 'password']);

});
