/*
 * Hume
 * This is an API for Hume
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto-generated by the Swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

// Import the module loader utility function
const configureModule = require('../moduleLoaderUtils');

// Use the module loader utility function to configure the module
configureModule(function (expect, Hume) {
  'use strict';

  // Variable to hold an instance of InvalidDeviceId
  var instance;

  // Test suite for the InvalidDeviceId
  describe('(package)', function() {
    describe('InvalidDeviceId', function() {

      // Setup a new instance before each test
      beforeEach(function() {
        instance = new Hume.InvalidDeviceId();
      });

      // Test case to check if it creates an instance of InvalidDeviceId
      it('should create an instance of InvalidDeviceId', function() {
        // TODO: update the code to test InvalidDeviceId
        expect(instance).to.be.a(Hume.InvalidDeviceId);
      });

      // Test case to check the 'code' property
      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      // Test case to check the 'message' property
      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

    });
  });

});
