/*
 * Hume
 * This is an API for Hume
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Hume);
  }
}(this, function(expect, Hume) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Hume.AlarmApi();
  });

  describe('(package)', function() {
    describe('AlarmApi', function() {
      describe('getAlarmStatus', function() {
        it('should call getAlarmStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlarmStatus call and complete the assertions
          /*
          var username = "username_example";
          var zoneId = 56;

          instance.getAlarmStatus(username, zoneId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Hume.AlarmResponse);
            expect(data.value).to.be.a('string');
            expect(data.value).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('modifyAlarmStatus', function() {
        it('should call modifyAlarmStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for modifyAlarmStatus call
          /*
          var alarmStatus = true;
          var username = "username_example";
          var zoneId = 56;

          instance.modifyAlarmStatus(alarmStatus, username, zoneId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
