/*
 * Hume
 * This is an API for Hume
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto-generated by the Swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

// Import the module loader utility function
const configureModule = require('../moduleLoaderUtils');

// Use the module loader utility function to configure the module
configureModule(function () {

  'use strict';

  // Variable to hold an instance of the AlarmApi
  var instance;

  // Setup a new instance before each test
  beforeEach(function() {
    instance = new Hume.AlarmApi();
  });

  // Test suite for the AlarmApi
  describe('(package)', function() {
    describe('AlarmApi', function() {
      
      // Test case for the getAlarmStatus method
      describe('getAlarmStatus', function() {
        it('should call getAlarmStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlarmStatus call, and complete assertions
          /*
          var username = "username_example";
          var zoneId = 56;

          instance.getAlarmStatus(username, zoneId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Hume.AlarmResponse);
            expect(data.value).to.be.a('string');
            expect(data.value).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });

      // Test case for the modifyAlarmStatus method
      describe('modifyAlarmStatus', function() {
        it('should call modifyAlarmStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for modifyAlarmStatus call
          /*
          var alarmStatus = true;
          var username = "username_example";
          var zoneId = 56;

          instance.modifyAlarmStatus(alarmStatus, username, zoneId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

});
