/*
 * Hume
 * This is an API for Hume
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto-generated by the Swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

// Immediately Invoked Function Expression (IIFE) to encapsulate code and prevent global scope pollution
(function(root, factory) {
  // Check for AMD (Asynchronous Module Definition) support
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.js
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Hume);
  }
}(this, function(expect, Hume) {
  'use strict';

  // Variable to hold an instance of the ContactDevsApi
  var instance;

  // Setup a new instance before each test
  beforeEach(function() {
    instance = new Hume.ContactDevsApi();
  });

  // Test suite for the ContactDevsApi
  describe('(package)', function() {
    describe('ContactDevsApi', function() {
      // Test case for the contactDevs method
      describe('contactDevs', function() {
        it('should call contactDevs successfully', function(done) {
          // TODO: uncomment, update parameter values for contactDevs call, and complete assertions
          /*
          var fullname = "fullname_example";
          var email = "email_example";
          var textMessage = "textMessage_example";
          var username = "username_example";

          instance.contactDevs(fullname, email, textMessage, username, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
