name: ci

on: 
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup mode
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download deps
        run: npm i
        
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Railway
        run: npm -i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service d6b9aed2-9c99-4680-8ffd-4fa6377316b4
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}